name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Install OpenCL (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y ocl-icd-opencl-dev opencl-headers
    - name: Install OpenCL (Windows)
      if: runner.os == 'Windows'
      run: choco install opencl-sdk -y
    - name: Get CMake
      uses: lukka/get-cmake@v3.26.0
    - name: Configure CMake
      run: cmake .
    - name: Build
      run: cmake --build . --config Release
    - name: Install
      run: cmake --install .
    - name: Add to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/Release-${{ matrix.target }}.zip
